// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQEGDO6FVTQRwlzueoUVDK0qjkHk3guao',
    appId: '1:38239925706:web:f4bb8ef4a91f69b40e0b33',
    messagingSenderId: '38239925706',
    projectId: 'cheekify-ce0c5',
    authDomain: 'cheekify-ce0c5.firebaseapp.com',
    storageBucket: 'cheekify-ce0c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaA4G8sDL3UcstWivUHgxCLocIsfsO2js',
    appId: '1:38239925706:android:e3616aef74e39bff0e0b33',
    messagingSenderId: '38239925706',
    projectId: 'cheekify-ce0c5',
    storageBucket: 'cheekify-ce0c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXChmeb-ULyGshfPLoZmn2cPHdcxGWK0',
    appId: '1:38239925706:ios:ec47f1c484484e9f0e0b33',
    messagingSenderId: '38239925706',
    projectId: 'cheekify-ce0c5',
    storageBucket: 'cheekify-ce0c5.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRXChmeb-ULyGshfPLoZmn2cPHdcxGWK0',
    appId: '1:38239925706:ios:ec47f1c484484e9f0e0b33',
    messagingSenderId: '38239925706',
    projectId: 'cheekify-ce0c5',
    storageBucket: 'cheekify-ce0c5.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQEGDO6FVTQRwlzueoUVDK0qjkHk3guao',
    appId: '1:38239925706:web:fa140b51750cfa3b0e0b33',
    messagingSenderId: '38239925706',
    projectId: 'cheekify-ce0c5',
    authDomain: 'cheekify-ce0c5.firebaseapp.com',
    storageBucket: 'cheekify-ce0c5.firebasestorage.app',
  );
}
